INSERT INTO chat(chat_title)  VALUES
  ('first chat'),
  ('second chat'),
  ('third chat');
INSERT INTO "user"(active, email, first_name, last_name, password, avatar_url_thumbnail, avatar_url_large)  VALUES
  (TRUE, 'admin@admin', 'Admin', 'Admin', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/23.jpg', 'https://randomuser.me/api/portraits/men/23.jpg'),
  (TRUE, 'isaac.duval@example.com', 'Isaac', 'Duval', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/23.jpg', 'https://randomuser.me/api/portraits/men/23.jpg'),
  (TRUE, 'evan.richards@example.com', 'Evan', 'Richards', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/50.jpg', 'https://randomuser.me/api/portraits/men/50.jpg'),
  (TRUE, 'gabriel.hudson@example.com', 'Gabriel', 'Hudson', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/92.jpg', 'https://randomuser.me/api/portraits/men/92.jpg'),
  (TRUE, 'rasmus.mortensen@example.com', 'Rasmus', 'Mortensen', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/68.jpg', 'https://randomuser.me/api/portraits/men/68.jpg'),
  (TRUE, 'annabelle.lam@example.com', 'Annabelle', 'Lam', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/women/48.jpg', 'https://randomuser.me/api/portraits/women/48.jpg'),
  (TRUE, 'ferdinand.bader@example.com', 'Ferdinand', 'Bader', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/17.jpg', 'https://randomuser.me/api/portraits/men/17.jpg'),
  (TRUE, 'luca.henry@example.com', 'Luca', 'Henry', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/76.jpg', 'https://randomuser.me/api/portraits/men/76.jpg'),
  (TRUE, 'liam.park@example.com', 'Liam', 'Park', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/29.jpg', 'https://randomuser.me/api/portraits/men/29.jpg'),
  (TRUE, 'eva.esteban@example.com', 'Eva', 'Esteban', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/women/18.jpg', 'https://randomuser.me/api/portraits/women/18.jpg'),
  (TRUE, 'ryan.denys@example.com', 'Ryan', 'Denys', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/87.jpg', 'https://randomuser.me/api/portraits/men/87.jpg'),
  (TRUE, 'margie.fernandez@example.com', 'Margie', 'Fernandez', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/women/81.jpg', 'https://randomuser.me/api/portraits/women/81.jpg'),
  (TRUE, 'nihal.vanhooff@example.com', 'Nihal', 'Van Hooff', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/women/66.jpg', 'https://randomuser.me/api/portraits/women/66.jpg'),
  (TRUE, 'angèle.giraud@example.com', 'Angèle', 'Giraud', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/women/10.jpg', 'https://randomuser.me/api/portraits/women/10.jpg'),
  (TRUE, 'solano.daconceição@example.com', 'Solano', 'Da Conceição', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/98.jpg', 'https://randomuser.me/api/portraits/men/98.jpg'),
  (TRUE, 'ewen.guillaume@example.com', 'Ewen', 'Guillaume', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/39.jpg', 'https://randomuser.me/api/portraits/men/39.jpg'),
  (TRUE, 'tracy.carpenter@example.com', 'Tracy', 'Carpenter', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/women/94.jpg', 'https://randomuser.me/api/portraits/women/94.jpg'),
  (TRUE, 'celina.patterson@example.com', 'Celina', 'Patterson', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/women/90.jpg', 'https://randomuser.me/api/portraits/women/90.jpg'),
  (TRUE, 'philippe.ouellet@example.com', 'Philippe', 'Ouellet', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/34.jpg', 'https://randomuser.me/api/portraits/men/34.jpg'),
  (TRUE, 'robin.lefebvre@example.com', 'Robin', 'Lefebvre', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/39.jpg', 'https://randomuser.me/api/portraits/men/39.jpg'),
  (TRUE, 'orandino.damota@example.com', 'Orandino', 'Da Mota', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/18.jpg', 'https://randomuser.me/api/portraits/men/18.jpg'),
  (TRUE, 'manon.barbier@example.com', 'Manon', 'Barbier', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/women/13.jpg', 'https://randomuser.me/api/portraits/women/13.jpg'),
  (TRUE, 'divo.moraes@example.com', 'Divo', 'Moraes', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/2.jpg', 'https://randomuser.me/api/portraits/men/2.jpg'),
  (TRUE, 'william.novak@example.com', 'William', 'Novak', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/36.jpg', 'https://randomuser.me/api/portraits/men/36.jpg'),
  (TRUE, 'asta.poulsen@example.com', 'Asta', 'Poulsen', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/women/82.jpg', 'https://randomuser.me/api/portraits/women/82.jpg'),
  (TRUE, 'lance.owens@example.com', 'Lance', 'Owens', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/13.jpg', 'https://randomuser.me/api/portraits/men/13.jpg'),
  (TRUE, 'philippe.ma@example.com', 'Philippe', 'Ma', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/55.jpg', 'https://randomuser.me/api/portraits/men/55.jpg'),
  (TRUE, 'phuong.bond@example.com', 'Phuong', 'Bond', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/women/22.jpg', 'https://randomuser.me/api/portraits/women/22.jpg'),
  (TRUE, 'malthe.jørgensen@example.com', 'Malthe', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'these', 'https://randomuser.me/api/portraits/thumb/men/79.jpg', 'https://randomuser.me/api/portraits/men/79.jpg'),
  (TRUE, 'debbie.smith@example.com', 'Debbie', 'Smith', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/women/48.jpg', 'https://randomuser.me/api/portraits/women/48.jpg'),
  (TRUE, 'valentin.bonnet@example.com', 'Valentin', 'Bonnet', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/0.jpg', 'https://randomuser.me/api/portraits/men/0.jpg'),
  (TRUE, 'jan.schwab@example.com', 'Jan', 'Schwab', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/12.jpg', 'https://randomuser.me/api/portraits/men/12.jpg'),
  (TRUE, 'daryl.sanders@example.com', 'Daryl', 'Sanders', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/65.jpg', 'https://randomuser.me/api/portraits/men/65.jpg'),
  (TRUE, 'aapo.joki@example.com', 'Aapo', 'Joki', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/97.jpg', 'https://randomuser.me/api/portraits/men/97.jpg'),
  (TRUE, 'melanie.beck@example.com', 'Melanie', 'Beck', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/women/70.jpg', 'https://randomuser.me/api/portraits/women/70.jpg'),
  (TRUE, 'robert.herrmann@example.com', 'Robert', 'Herrmann', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/85.jpg', 'https://randomuser.me/api/portraits/men/85.jpg'),
  (TRUE, 'felipe.benitez@example.com', 'Felipe', 'Benitez', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/24.jpg', 'https://randomuser.me/api/portraits/men/24.jpg'),
  (TRUE, 'gretha.tempels@example.com', 'Gretha', 'Tempels', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/women/1.jpg', 'https://randomuser.me/api/portraits/women/1.jpg'),
  (TRUE, 'logan.vidal@example.com', 'Logan', 'Vidal', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/77.jpg', 'https://randomuser.me/api/portraits/men/77.jpg'),
  (TRUE, 'jade.wong@example.com', 'Jade', 'Wong', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/women/44.jpg', 'https://randomuser.me/api/portraits/women/44.jpg'),
  (TRUE, 'mark.reed@example.com', 'Mark', 'Reed', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/34.jpg', 'https://randomuser.me/api/portraits/men/34.jpg'),
  (TRUE, 'isabella.christensen@example.com', 'Isabella', 'Christensen', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/women/28.jpg', 'https://randomuser.me/api/portraits/women/28.jpg'),
  (TRUE, 'ryder.hughes@example.com', 'Ryder', 'Hughes', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/16.jpg', 'https://randomuser.me/api/portraits/men/16.jpg'),
  (TRUE, 'titouan.hubert@example.com', 'Titouan', 'Hubert', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/17.jpg', 'https://randomuser.me/api/portraits/men/17.jpg'),
  (TRUE, 'kaylee.mills@example.com', 'Kaylee', 'Mills', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/women/92.jpg', 'https://randomuser.me/api/portraits/women/92.jpg'),
  (TRUE, 'harrison.wood@example.com', 'Harrison', 'Wood', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/18.jpg', 'https://randomuser.me/api/portraits/men/18.jpg'),
  (TRUE, 'miguel.fisher@example.com', 'Miguel', 'Fisher', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/men/6.jpg', 'https://randomuser.me/api/portraits/men/6.jpg'),
  (TRUE, 'anna.lemaire@example.com', 'Anna', 'Lemaire', '$2a$04$4bQtWLN03fkeexJ7ySCK5OhrqatPkvqaHPIier.38t/mRzRvjWOi.', 'https://randomuser.me/api/portraits/thumb/women/0.jpg', 'https://randomuser.me/api/portraits/women/0.jpg');

INSERT INTO message(content, created_at, chat_id, read, sender_id) VALUES
  ('Hi','1999-01-08 04:05:06',1,TRUE, 1),
  ('Hi1','1999-01-08 04:05:08',1,TRUE, 1),
  ('Hi2','1999-01-08 04:05:10',1,FALSE, 2),
  ('Hi3','1999-01-08 04:05:12',2,TRUE, 3),
  ('Hi4','1999-01-08 04:05:15',2,TRUE, 4),
  ('Hi5','1999-01-08 04:05:18',3,FALSE, 1),
  ('Hi6','1999-01-08 04:05:19',3,FALSE, 1);
INSERT INTO user_chat(chat_id, user_id) VALUES
  (1,1),
  (1,2),
  (2,3),
  (2,4),
  (3,1),
  (3,4);
